### ISSUE TITLE
Build tools, css, project structure, etc.

### ISSUE THREAD

**Issue by gjlaubenstein** [cyclejs-community/cycle-ui-kit#13]
Do we have a general direction on if we are using webpack or gulp? SCSS, LESS? 

I think we should determine our tooling and project structure before diving further into component development. Might be hard to go back and patch styling, file organization, etc. onto every component.

I was hoping we could use this issue to flush this out and open a new issue to add build tasks, styling and project structure.

@cyclejs-community/contributors

**Comment by gjlaubenstein** [comment]
Nevermind just read https://github.com/cyclejs-community/cycle-ui-kit/issues/2

**Comment by artfuldev** [comment]
@eshansingh decides most of it here, although you can take to #2 to speak your mind.

**Comment by eshansingh** [comment]
I've decided to use npm scripts as are "build tool". I'm open to using gulp or something else, but only if someone submits a PR or something with translations for the currently available tasks. I'm looking into webpack for bundling. Another solution could be a CLI in which you can say `cycle-ui-kit add SomeComponent:material`. Suggestions?

**Comment by eshansingh** [comment]
In addition, I think using sass (or scss) is a better deal, because it'll be way more useful IMHO.

**Comment by gjlaubenstein** [comment]
@eshansingh I can open a PR adding sass or scss today/tomorrow if thats the route to take.

would the `cycle-ui-kit add SomeComponent:material` in theory work like a rails generator?

**Comment by eshansingh** [comment]
@gjlaubenstein Sort of.

**Comment by eshansingh** [comment]
@gjlaubenstein I really do appreciate a PR, however be aware that I will only be able to actively work on the project on Sundays (or Mondays depending on your timezone).

**Comment by leesiongchan** [comment]
When would the basic structure and stuff coming out? Would like to use and contribute.

**Comment by leesiongchan** [comment]
And why not consider PostCSS + CSS modules?

**Comment by eshansingh** [comment]
@leesiongchan There's currently a lot going on right now for me, I know this repo has remained stagnant for a while now, but I'll get back to this and other important questions next week, I promise.

**Comment by eshansingh** [comment]
@leesiongchan 

So, a few things:

- I've never really looked into PostCSS properly, but looking at the wide variety of plugins and toolkits available, I'll say it's a pretty good bet. And the thing is, no contributor has to learn the (somewhat) weird indented Sass syntax. I think we can run with it.
- I'm just using `npm` scripts as build "tools". I don't think there will be any need for anything too complex.
- Components will use MVI, and the model and intent will be in the base. The view will be defined by the "skins".

Suggestions?
