### ISSUE TITLE
Package choices

### ISSUE THREAD

**Issue by artfuldev** [cyclejs-community/cycle-ui-kit#3]
There are a couple of packages used here, the uses of which, not everybody understands.
For example, this is the first project where I'm seeing "xo" or "ava" as a dependency. It would be helpful if we can take the time to explain/debate on some choices that we make. This will be a closed issue, as it is a discussion.

**Comment by artfuldev** [comment]
What is xo and why do we have to use it?

**Comment by artfuldev** [comment]
Why are we using TypeScript?
http://staltz.com/all-js-libraries-should-be-authored-in-typescript.html

**Comment by eshansingh** [comment]
👍 TypeScript because of the type support. I'm sure you agree on that.
[XO](https://github.com/sindresorhus/xo) is basically just a linter. It uses ESLint under the hood. I'm a big fan of it because of its built-in config and easy-to-use CI.
[Ava](https://github.com/avajs/ava) is a test runner that can run tests asychronously. I'm open to other suggestions. While I understand Mocha is popular, I think it'll be overkill for this project.

**Comment by Widdershin** [comment]
TypeScript is cool, but I wonder if we might have more potential contributors if we author in JavaScript. Just something to think about.

**Comment by eshansingh** [comment]
All the current Cycle.js repos are authored in TypeScript. Besides, TypeScript isn't really all that different from JavaScript other than three things: types, interfaces, and generics.

**Comment by Widdershin** [comment]
Fair enough. Perhaps we could have a repo to help beginners learn about TypeScript, or at least a collection of resources for where to start.

**Comment by eshansingh** [comment]
That is a good idea, but I think it's for another day.

**Comment by eshansingh** [comment]
How do you think we should test today?

**Comment by Widdershin** [comment]
Personally I use `mocha` for all my projects, because it's trivial to set up, supports `--watch` out of the box, and I find the syntax familiar.

I don't bother with `chai` or `sinon`, I just use `assert` and I don't write code that needs mocks.

I haven't used `ava` but I've heard good things.

**Comment by eshansingh** [comment]
(P.S actually let me set up a gitter chat for this, give me a second)

**Comment by eshansingh** [comment]
Done. https://gitter.im/cyclejs-community/cycle-ui-kit
